import React, { useState } from 'react';

const DogBreedSelect = ({ onBreedChange }) => {
  const [breed, setBreed] = useState('');
  const breeds = [  "Affenpinscher",
    "Afghan Hound",
    "Africanis",
    "Aidi",
    "Airedale Terrier",
    "Akita",
    "Alabai",
    "Alano Español",
    "Alaskan Klee Kai",
    "Alaskan Malamute",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Eskimo Dog",
    "American Foxhound",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd",
    "Andalusian Hound",
    "Australian Cattle Dog",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Silky Terrier",
    "Australian Terrier",
    "Azawakh",
    "Basset Artesien Normand",
    "Basset Bleu de Gascogne",
    "Basset Fauve de Bretagne",
    "Basset Hound",
    "Bavarian Mountain Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Laekenois",
    "Belgian Malinois",
    "Belgian Shepherd",
    "Belgian Tervuren",
    "Bergamasco",
    "Berger Picard",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Black Mouth Cur",
    "Black Norwegian Elkhound",
    "Black Russian Terrier",
    "Black Swedish Vallhund",
    "Bloodhound",
    "Blue Heeler",
    "Blue Lacy",
    "Blue Picardy Spaniel",
    "Blue Ridge Spaniel",
    "Boerboel",
    "Bohemian Shepherd",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Braque du Bourbonnais",
    "Braque Français",
    "Briard",
    "Brittany Spaniel",
    "Broholmer",
    "Brussels Griffon",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Cairn Terrier",
    "Canaan Dog",
    "Canadian Eskimo Dog",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Catahoula Leopard Dog",
    "Caucasian Shepherd",
    "Cavalier King Charles Spaniel",
    "Central Asian Ovtcharka",
    "Cesky Fousek",
    "Cesky Terrier",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Chongqing Dog",
    "Chinese Crested",
    "Chinese Shar-Pei",
    "Chinook",
    "Chow Chow",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Collie",
    "Coton de Tulear",
    "Curly-Coated Retriever",
    "Czechoslovakian Vlcak",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Danish-Swedish Farmdog",
    "Dobermann",
    "Dogo Argentino",
    "Dogo Canario",
    "Dogue de Bordeaux",
    "Dutch Shepherd",
    "Dutch Smoushond",
    "English Bulldog",
    "English Cocker Spaniel",
    "English Coonhound",
    "English Foxhound",
    "English Mastiff",
    "English Setter",
    "English Shepherd",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "Entlebucher Mountain Dog",
    "Eskimo Dog",
    "Estrela Mountain Dog",
    "Eurasier",
    "Field Spaniel",
    "Finnish Hound",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "French Basset Hound",
    "French Bulldog",
    "French Spaniel",
    "French Tricolour Hound",
    "Gaddi Kutta",
    "Garafian Shepherd",
    "Gascon Saintongeois",
    "German Hound",
    "German Longhaired Pointer",
    "German Pinscher",
    "German Roughhaired Pointer",
    "German Shepherd",
    "German Shorthaired Pointer",
    "German Spaniel",
    "German"
  ];

  const handleBreedChange = (event) => {
    setBreed(event.target.value);
    onBreedChange(event.target.value);
  };

  return (
    <select value={breed} onChange={handleBreedChange}>
      {breeds.map((breed) => (
        <option key={breed} value={breed}>
          {breed}
        </option>
      ))}
    </select>
  );
};

export default DogBreedSelect;
